### PR TITLE
JDK7 and FS 5.1R4 readyness

### PR DESCRIPTION
**Pull request by Martin-Aulich**
Hey Guys,

I took the liberty to remove deprecation warnings in FS 5.1R4 and update the Maven POM to support JDK7. I also removed compiler errors in the test classes with FS 5.1R4.

Furthermore I tried to tidy up the code a little (i.e. remove unnecessary typing towards concrete classes instead of interfaces, used generics instead of raw types, etc.).

If there is anything to discuss, please contact me.

Regards,
Martin

### CODE REVIEW

**Comment by feddersen-espirit** [comment]
Hi Martin,
thank you very much for your pull request!
We'll have to maintain a version that is compatible with FirstSpirit 5.0. Our current plan is to do that in a new branch and merge your changes into the master. 
I'll get back to you next week!

Christoph

**Comment by zaplatynski-espirit** [comment]
Hi Martin,

I have checked your pull request. It looks good, thank you very much! Unfortunately, we still need to support Java 6, because FirstSpirit 5.1 does still support Java 6. Could you please be so kind to change your pull request so it will be compatible with Java 6?

Regards,
Marian

**Comment by Martin-Aulich** [comment]
Sorry for not responding sooner, but I'm currently quite busy...
I'll try to take care of Java-6 compliance soon.

Is a multi-branch strategy planned in order to take advantage of Java-7 or even Java-8 features?

Regards,
Martin

**Comment by zaplatynski-espirit** [comment]
Hi Martin,

since we need to support all releases from FirstSpirit 5.1 to coming soon FirstSpirit 5.2 in autumn 2015 the short answer is no. But you are welcomed to do so. There is no problem if you want to maintain a Java 8 only branch of the basic workflows in your own repository. By the way, we merged some of your suggestions into the basic workflows' new version 1.0.8. Feel free to pull the changes.

Regards,
Marian

**Pull request closed without merging**
